services:
  joplin_db:
    image: postgres:16
    container_name: joplin_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: joplin
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: joplin
    volumes:
      - joplin_db_data:/var/lib/postgresql/data
    networks:
      - joplin_net

  joplin_server:
    image: joplin/server:latest
    container_name: joplin_server
    restart: unless-stopped
    depends_on:
      - joplin_db
    ports:
      - "22300:22300"
    environment:
      APP_BASE_URL: http://10.10.15.103:22300
      APP_PORT: 22300
      DB_CLIENT: pg
      POSTGRES_HOST: joplin_db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: joplin
      POSTGRES_USER: joplin
      POSTGRES_PASSWORD: joplin
    networks:
      - joplin_net

  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: whisper
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      WHISPER__MODEL: large-v3
      WHISPER__INFERENCE_DEVICE: cpu
    volumes:
      - whisper_models:/root/.cache/huggingface
    networks:
      - joplin_net

volumes:
  joplin_db_data:
  whisper_models:

networks:
  joplin_net:
